### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by skodapetr** [signus-game/signus#17]
As of now (release v1.96.0) "user home directory" is used as folder where Signus' data are saved - _saved games_, _crashguard_saved_state_ and _signus.ini_. It would be nice to have an option that would allow to store this data in the signus directory - making it "portable". It would also make it easier for users to find and share _crashguard_saved_state_ .

**Comment by Tony763** [comment]
Perhaps add arg with path to save directory? Something like 'signus --save-dir ./savedir'?

**Comment by skodapetr** [comment]
I would go with higher level, like ```--data-dir``` as it is not only saves, but the signus.ini file and the _crashguard_saved_state _.

**Comment by skodapetr** [comment]
Perhaps an alternative, easier for implementation, would be to add another env. variable. Then it can be just read before the env. variable for home. The user comfort in that case can be provided by a bat/sh file that will set the current directory to this new env. variable.

**Comment by kukenc** [comment]
Game already use env var, this is better way IMHO. But not sure, if `APPDATA` or `--data-dir` is not confusing. Signus have many data build from folder `signus-data` and installed to `/usr/share/signus/1.96/` at linux (dont know how it works on windows).

**Comment by skodapetr** [comment]
```APPDATA``` is used on Windows for the user home app-directory, so it is standard way. I've just abuse it to get the job done. 

On Win you just download it as an archive and unpack. Then thanks to using the ```APPDATA``` all the files mentioned in the first post are saved correctly to the ```user-home/app-data/......``` directory. For most users this is how it should be done - although there are now new folders (Saved Games, some games use Documents, ...). 

I my case I was fine, although curious,  until I've encountered bug in mission 5 and need to manually remove the crash file. I also like to keep my save files together with my games, especially the older ones that are not automatically synced to cloud. So in case of re-install of the OS I do not lose them.

**Comment by nextghost** [comment]
I'll add a message box asking whether to load crashguard save or ignore it and open main menu as usual. That'll solve the problem of infinite crash loops without the need to delete it manually.

However, a portable version where the executable, game data, configs and saved games are all stored in the same directory is not a priority for me. If anybody wants to send a patch, the best option is to use conditional compilation, build separate executables with different hardcoded paths and make a new portable ZIP archive which will bundle executables for all supported platforms. Juggling different paths via command line arguments or env variables will just confuse users who accidentaly run the executable directly instead of the special BAT file or shell script.

The path detection code is in `signus/src/unix.cpp` and `signus/src/windows.cpp`, respectively.
