### ISSUE TITLE
Screen frozen_mission 5__AI move

### ISSUE THREAD

**Issue by Johnyy88** [signus-game/signus#22]
Hi, I downloaded "signus-1.96.0-win64" and played until in mission 5 the screen got frozen after pressing the END ROUND button. Each time I restart the game, its gets me directly bact to this frozen screen. Adding the "crashguard_saved_state" to analyze the issue. Thx very much for looking into this!

[crashguard_saved_state.zip](https://github.com/signus-game/signus/files/12480555/crashguard_saved_state.zip)

![mission 5__screen frozen](https://github.com/signus-game/signus/assets/143661522/95b35b7b-708a-451d-9d43-0d28125e6cd4)

**Comment by nextghost** [comment]
Thanks for the report. I can see from the crashguard save that one of the missile turrets at the enemy base is out of ammo and needs to retract to reload. But it also has viable targets so it immediately tries to deploy and fire again. But it doesn't have enough time units to do that and the AI code doesn't check that, resulting in infinite loop of failed deployment attempts.

I've pushed the fix to repo but I don't want to make a full release right now. I can see that you're right at the start of mission 5. Do you have an older savegame you could continue from? If you delete or rename the `crashguard_saved_state` file, the game will start normally and open the main menu. You can then avoid this bug by moving all your units out of the missile turret range at least once every 4 turns so that they retract and reload before running out of ammo.

**Comment by nextghost** [comment]
I've published [bugfix patch v1.96.1](https://github.com/signus-game/signus/releases/tag/v1.96.1) which includes fix for this issue. Closing.
